### PR TITLE
Upgrade to new semver-parser

### PR DESCRIPTION
**Pull request by steveklabnik**
@udoprog, I've released a 0.9.0 of semver-parser with your parser in it. I was also looking at https://github.com/steveklabnik/semver/pull/151. Here's the result. I have concerns:

1. These error messages seem *way* worse
2. The regression suite now panics

Any thoughts here? I'm second-guessing the decision, to be honest.

### CODE REVIEW

**Comment by udoprog** [comment]
Hey!

I'll discuss the issues raised, if you want to revert that is ultimately up to you. I'm willing to help out in any way you see fit.

**1)** The error message thing was discussed in the [semver-parser PR](https://github.com/steveklabnik/semver-parser/pull/34#issuecomment-350361925) - relevant issue opened here: https://github.com/steveklabnik/semver-parser/issues/37

A simple and contextual way we can address this is by adding `.map_err(...)` into more specific error types in places like these: https://github.com/steveklabnik/semver-parser/blob/master/src/parser.rs#L399

**2)** The regression seems to be due to a difference in parsing. We will treat `0.2` and `*` as separate predicates, but we also seem to discard wildcard predicates - probably because they are meaningless. This can be patched in semver-parser by enforcing that the two groups should be separated by whitespace somewhere around here:
https://github.com/steveklabnik/semver-parser/blob/master/src/parser.rs#L162

That aside, I was holding off for a merge of semver-parser` and `semver` as discussed in #125 before doing this. It's a pain having to synchronize two such highly coupled projects for releases.

**Comment by infinity0** [comment]
Any chance this is going to be resolved soon? This is soft-blocking us in Debian.

**Comment by steveklabnik** [comment]
@infinity0 yes and no; that is, I have been working on this, but it's taken a semi-backburner; if I can understand more how this is blocking, then I can prioritize work to resolve it. This stuff is for an unreleased version, so I'm not sure how it's blocking you all?

**Comment by infinity0** [comment]
debcargo is using semver 0.9 which uses semver-parser 0.7 but we've already packaged semver-parser 0.9 in Debian. It would be nice not to have to carry both versions although we technically can, and it's faster because we don't have to wait for the Debian FTP team to do a copyright review - which is trivial in this case, but they have a very long queue of other packages to do.

**Comment by kpcyrd** [comment]
are there any updates regarding this issue?

**Comment by infinity0** [comment]
what actually is the problem here, and why are there even two semver crates with very similar data structures in the first place?

**Comment by sunshowers** [comment]
Just a note for whenever this is picked up -- this is a compatibility breakage so this change would require a new semver-incompatible version. That's because the conversion from `semver_parser::range::VersionReq` to `semver::VersionReq` is exposed to the public via a `From` impl. (You could maintain semver compatibility by including both semver_parser 0.7 and 0.9 as dependencies, but that seems wasteful.)

I agree that this could probably be combined into a single crate though.

**Comment by steveklabnik** [comment]
This isn't going to end up getting merged. I'll explain the plan at some point.

**Pull request closed without merging**
