### PR TITLE
Add Eq trait in main error

### PR DESCRIPTION
**Pull request by tredoe**

### CODE REVIEW

**Comment by dtolnay** [comment]
What is the motivation for this? Are you using SemVerError as a key in a HashMap or something? Could you share the code you wanted to write where PartialEq was not sufficient?

**Comment by tredoe** [comment]
It was to testing errors; to be able sure than a function returns a specific error.
But I've been advised about comparing the errors as strings.

**Comment by dtolnay** [comment]
PartialEq and Debug should be all you need for checking equality in a test.

```rust
#[derive(PartialEq, Debug)]
pub enum SemVerError {
    ParseError(String),
}

fn main() {
    let expected = SemVerError::ParseError("a".to_owned());
    let actual = SemVerError::ParseError("b".to_owned());
    assert_eq!(expected, actual);
}
```

**Comment by tredoe** [comment]
The issue is when you have an enum/struct with some error which can not be compared like happens in serde_json::Error:

https://github.com/serde-rs/json/issues/271#issuecomment-283526261

**Comment by tredoe** [comment]
According to Rust community, it is better to use macro `assert_matches!` to checking errors.

**Pull request closed without merging**
