### PR TITLE
rustfmt all the things

### PR DESCRIPTION
**Pull request by udoprog**
Format all files and introduce a Travis build step that verifies formatting.

### CODE REVIEW

**Comment by KodrAus** [comment]
Personally, I'm on board with doing this :+1: What do you think @steveklabnik?

It's a lot of churn, but if we're going to support formatting then it's a bit inevitable for the first commit. Does anyone happen to know if the `rustfmt-nightly` tool differs w.r.t. formatting from the old `rustfmt`?

**Comment by udoprog** [comment]
Oh wow. The build time checks took 38 minutes to run now (up from 12m) since it needs to install rustfmt. Including it might not be a good idea.

**Comment by KodrAus** [comment]
Adding a build cache to Travis should get that compile time back down again.

**Comment by udoprog** [comment]
@KodrAus good point!

**Pull request merged**
