### PR TITLE
Libz blitz/turn references to other semver items int links

### LINKED ISSUE #132: Turn references to other `semver` items into links
[Relevant API guidelines](https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-link)

Where there are references to types in the crate documentation (like the references to `Version` [here](https://docs.rs/semver/0.9.0/semver/#versions)) we should convert them into links to that type so users can find their way around the crate more easily.

### PR DESCRIPTION
**Pull request by muzikmoe**
Should resolve #132

### CODE REVIEW

**Comment by KodrAus** [comment]
Thanks @muzikmoe!

It'd be helpful if we could use separate branches for each of these PRs that's just based off master with the commit that fixes the issue. That way it'll be easier to review the code for the specific issue you're fixing :)

Are you able to cherry pick commit `422230a` onto a new branch that's based off `master`? I'm happy to guide you through it if you'd like a hand.

We should do the same for the other PRs you've opened (thanks again for tackling these issues!)

**Comment by muzikmoe** [comment]
@KodrAus Thank for your guiding, I am sorry for bothering you with these formless pull requests.
If I get your point, do you mean the following branch structure?
`orgin_master` (the most original base before my first commit)
```
origin_master => libz_blitz: html_root_url_attribute_to_crate_root
origin_master => libz_blitz: use_question_mark_instead_of_unwrap_in_examples
origin_master => libz_blitz: turn_references_to_other_semver_items_int_links 
```

**Comment by KodrAus** [comment]
That's the one! And it's absolutely no problem or bother at all. We appreciate your contributions :) It'll just be easier down the track when @steveklabnik is ready for a look.

**Comment by muzikmoe** [comment]
rebased.
check out #145

**Pull request closed without merging**
