### PR TITLE
Implement Hash, Eq, and Ord for VersionReq

### PR DESCRIPTION
**Pull request by udoprog**
Hey,

I recently started using VersionReq to perform artifact lookup, and I needed to build a cache of what a given package + version requirement resolved into.

Because VersionReq doesn't implement `Eq`, or `Hash`, this was not entirely straight forward.

This is not a perfect solution, I realize that there might be multiple version requirements which are semantically equivalent (like `1.*` vs `1.*.*`) and that the naive Hash and Eq implementation does not take this into account. But for my purposes, this is good enough.

An alternative would be to expose functions that permit implementing these in newtypes, preferably without having to resort to some hack like converting to string during comparisons.

If there are other alternatives, I would love to know!

### CODE REVIEW

**Comment by steveklabnik** [comment]
Hi there!

Eq is tough; I'm not actually sure that versions form a partial or total order. This doesn't mean it does or doesn't, but I haven't thought it through yet. That's why I'm lagging on this PR.

**Comment by udoprog** [comment]
Hey!

If it wasn't a mistype, I'm not sure it's required to determine if versions form a total order or not. This PR should only affect version requirements unless I'm missing something?

Ordering of version requirements is defined by how the collection of predicates sort. It shouldn't have any particular meaning beyond `predicate x sorts before y because that is how it's defined`. I hope this helps.

**Comment by steveklabnik** [comment]
> If it wasn't a mistype, I'm not sure it's required to determine if versions form a total order or not. This PR should only affect version requirements unless I'm missing something?

It is and it isn't, that is, if versions don't form a total order, can requirements? Maybe I am over-thinking it 😄 

*that* said, requirements can't actually contain full versions, so maybe that's where I'm going wrong thinking about this.

**Comment by udoprog** [comment]
> It is and it isn't, that is, if versions don't form a total order, can requirements?

Ok! I can put the `Ord` implementation in a separate PR so we can do `Eq` and `Hash` now, assuming they are less controversial :smile:.

**Comment by steveklabnik** [comment]
`Eq` has the same problem, is it total or not?

`Hash` isn't, heh.

Honestly, I am probably over-thinking the whole thing and should just go for it; it just seems like this is a big commitment. Maybe it isn't.

**Comment by udoprog** [comment]
Not sure I get it. But feel free to take your time thinking about it. Thanks for poking me.

**Comment by Arnavion** [comment]
>it just seems like this is a big commitment

You can avoid commitment by adding a `struct ExactlyEqual(VersionReq)` and impl for that. (similar to what @udoprog alluded to this in the first post). That way you don't set the behavior for `VersionReq` itself in stone. If you later do think that `ExactlyEqual` semantics work for `VersionReq` then you could impl for it and deprecate `ExactlyEqual`

**Comment by steveklabnik** [comment]
In retrospect, I'm fine with this. Thank you for putting up with me being a little unsure here. I think the `Version` question is harder, but `VersionReq` makes sense to me, thank you!

**Pull request merged**
