### PR TITLE
Update the url to the semver doc

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by sourcefrog** [comment]
As I mentioned on https://github.com/steveklabnik/semver/pull/199#issuecomment-595349595, the old URL also occurs in some other files.

**Comment by sylvestre** [comment]
@steveklabnik Could you please merge it? Thanks :)

**Comment by sourcefrog** [comment]
This one's obsolete now and could be closed - #199 was merged.

**Comment by steveklabnik** [comment]
Whoops! Sorry for not merging this one :(

**Pull request closed without merging**
