### PR TITLE
Libz blitz/use question mark instead of unwrap in examples

### LINKED ISSUE #129: Use `?` instead of `unwrap` in examples
[Relevant API guidelines](https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-question-mark)

Replace uses of `.unwrap` in examples with `?` so they're a bit more idiomatic. Have a look at the API guideline examples for some ideas on how to do this.

### PR DESCRIPTION
**Pull request by opilar**
Rebased #144 
Resolves #129

### CODE REVIEW

**Comment by KodrAus** [comment]
Thanks for this @opilar :+1:

**Comment by apopiak** [comment]
This is done and will be merged, right? (Was thinking about picking this up)

**Comment by opilar** [comment]
@apopiak yes, it's done. Waiting to be merged.

**Comment by opilar** [comment]
@steveklabnik thank you!

**Pull request merged**
